### ISSUE TITLE
其他油猴脚本引用此库时若// @grant    不为 none 则不生效

### ISSUE THREAD

**Issue by XiaoMiku01** [xfgryujk/bliveproxy#1]
若脚本需要调用油猴的GM方法 // @grant    不能为none 这和此库冲突，望作者修复或改善！

**Comment by xfgryujk** [comment]
脚本的权限和库的权限有关吗

**Comment by XiaoMiku01** [comment]
似乎没有关系，好像是只要引用作者您这个库 grant 就必须指定为none 才能生效，即使官网文档说 不指定 和none是等效的

**Comment by xfgryujk** [comment]
我知道了，应该是加了grant会运行在沙箱环境
